# Generated by Django 4.1.3 on 2022-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["id"],
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
            },
        ),
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
