# Generated by Django 4.1.3 on 2022-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_dish_options_alter_dish_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "dishes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="ingredients",
                        to="restaurant.dish",
                    ),
                ),
            ],
        ),
    ]
