# Generated by Django 4.1.3 on 2022-11-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_ingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cook",
            options={
                "ordering": ["username"],
                "verbose_name": "cook",
                "verbose_name_plural": "cooks",
            },
        ),
    ]
